spring.application.name=Sistema Gerenciamento de Mercadorias e Vendas

spring.datasource.url=jdbc:postgresql://localhost:5432/sisgesmv
spring.datasource.username=postgres
spring.datasource.password=32321132
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Substitua por uma chave Base64 com pelo menos 48 caracteres (384 bits)
jwt.secret=3kV+dcBd4cTTflUw7DbnB1T1Bp6jJebjVUXiMzFeTtJgRnOSyK0HbEdEj1vjW0hk
jwt.expiration=604800000

spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/